//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cb.Localization.resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class labels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal labels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cb.Localization.resources.labels", typeof(labels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập.
        /// </summary>
        internal static string btnLogin {
            get {
                return ResourceManager.GetString("btnLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logo dưới.
        /// </summary>
        internal static string enuBannerPosition_logo_bottom {
            get {
                return ResourceManager.GetString("enuBannerPosition_logo_bottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logo trái.
        /// </summary>
        internal static string enuBannerPosition_logo_left {
            get {
                return ResourceManager.GetString("enuBannerPosition_logo_left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trang chính.
        /// </summary>
        internal static string enuBannerPosition_main {
            get {
                return ResourceManager.GetString("enuBannerPosition_main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VNĐ.
        /// </summary>
        internal static string enuCostId_dong {
            get {
                return ResourceManager.GetString("enuCostId_dong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lượng.
        /// </summary>
        internal static string enuCostId_luongSJC {
            get {
                return ResourceManager.GetString("enuCostId_luongSJC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tỉ VNĐ.
        /// </summary>
        internal static string enuCostId_tidong {
            get {
                return ResourceManager.GetString("enuCostId_tidong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to triệu.
        /// </summary>
        internal static string enuCostId_trieudong {
            get {
                return ResourceManager.GetString("enuCostId_trieudong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USD.
        /// </summary>
        internal static string enuCostId_usd {
            get {
                return ResourceManager.GetString("enuCostId_usd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banner.
        /// </summary>
        internal static string enulogoPosition_logo_left {
            get {
                return ResourceManager.GetString("enulogoPosition_logo_left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên công ty.
        /// </summary>
        internal static string ltrCompanyName {
            get {
                return ResourceManager.GetString("ltrCompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string ltrEmail {
            get {
                return ResourceManager.GetString("ltrEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Điện thoại.
        /// </summary>
        internal static string ltrTel {
            get {
                return ResourceManager.GetString("ltrTel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên đăng nhập.
        /// </summary>
        internal static string statement_username {
            get {
                return ResourceManager.GetString("statement_username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiển thị.
        /// </summary>
        internal static string strAdminPublish {
            get {
                return ResourceManager.GetString("strAdminPublish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khóa lại.
        /// </summary>
        internal static string strAdminUnpublish {
            get {
                return ResourceManager.GetString("strAdminUnpublish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email của bạn.
        /// </summary>
        internal static string strEmail {
            get {
                return ResourceManager.GetString("strEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hình ảnh.
        /// </summary>
        internal static string strImage {
            get {
                return ResourceManager.GetString("strImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên.
        /// </summary>
        internal static string strName {
            get {
                return ResourceManager.GetString("strName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sắp xếp.
        /// </summary>
        internal static string strOrdering {
            get {
                return ResourceManager.GetString("strOrdering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trang.
        /// </summary>
        internal static string strPage {
            get {
                return ResourceManager.GetString("strPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vị trí.
        /// </summary>
        internal static string strPosition {
            get {
                return ResourceManager.GetString("strPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhóm quyền.
        /// </summary>
        internal static string strRoleName {
            get {
                return ResourceManager.GetString("strRoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu.
        /// </summary>
        internal static string strSave {
            get {
                return ResourceManager.GetString("strSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm kiếm.
        /// </summary>
        internal static string strSearch {
            get {
                return ResourceManager.GetString("strSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        internal static string strSiteName {
            get {
                return ResourceManager.GetString("strSiteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật.
        /// </summary>
        internal static string strUpdate {
            get {
                return ResourceManager.GetString("strUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày cập nhật.
        /// </summary>
        internal static string strUpdateDate {
            get {
                return ResourceManager.GetString("strUpdateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tải lên.
        /// </summary>
        internal static string strUpload {
            get {
                return ResourceManager.GetString("strUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiếng Việt.
        /// </summary>
        internal static string strVietNam {
            get {
                return ResourceManager.GetString("strVietNam", resourceCulture);
            }
        }
    }
}
